name: TryHackMe Update Badge

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  tryhackme-badge-update:
    name: "thm_propic.png"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          username: "H4K3R0S"
          GITHUB_TOKEN: ${{secrets.940714baedcbf541eda88f61}}
